apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
- route.yaml
patchesStrategicMerge:
- deployment.yaml
- ClusterRoleBinding.yaml
- self-provisioners.yaml
# - route.yaml

